/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WawaOffice.glb 
*/
import { useRef, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

const FLOOR_HEIGHT = 2.3;
const NUN_FLOORS = 3;

function Office(props) {
  const { nodes, materials } = useGLTF("/models/WawaOffice.glb");
  const buildingRef = useRef();
  const libraryRef = useRef();
  const atticRef = useRef();
  const tl = useRef();
  const scroll = useScroll();

  useFrame(() => {
    if (tl.current) {
      tl.current.seek(scroll.offset * tl.current.duration());
    }
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // building vertical animation
    tl.current.to(buildingRef.current.position, {
      duration: 2,
      y: -FLOOR_HEIGHT * (NUN_FLOORS - 1),
    });

    // building rotation
    tl.current.to(
      buildingRef.current.rotation,
      { duration: 1, x: 0, y: Math.PI / 6, z: 0 },
      0
    );
    tl.current.to(
      buildingRef.current.rotation,
      { duration: 1, x: 0, y: -Math.PI / 6, z: 0 },
      1
    );

    // building movement
    tl.current.to(
      buildingRef.current.position,
      {
        duration: 1,
        x: -1,
        z: 2,
      },
      0
    );
    tl.current.to(
      buildingRef.current.position,
      {
        duration: 1,
        x: 1,
        z: 2,
      },
      1
    );

    // library animation
    tl.current.from(
      libraryRef.current.position,
      {
        duration: 0.5,
        x: -2,
      },
      0.5
    );
    tl.current.from(
      libraryRef.current.rotation,
      {
        duration: 0.5,
        y: Math.PI / 2,
      },
      0
    );

    // attic animation
    tl.current.from(
      atticRef.current.position,
      {
        duration: 1.5,
        y: 2,
      },
      0
    );
    tl.current.from(
      atticRef.current.rotation,
      {
        duration: 0.5,
        y: Math.PI / 2,
      },
      1
    );
    tl.current.from(
      atticRef.current.position,
      {
        duration: 0.5,

        z: -2,
      },
      1.5
    );
  }, []);

  return (
    <group
      {...props}
      dispose={null}
      ref={buildingRef}
      position={[0.5, -1, -1]}
      rotation={[0, -Math.PI / 3, 0]}
    >
      <mesh geometry={nodes["01_office"].geometry} material={materials["01"]} />

      <group position={[0, 2.114, -2.23]} ref={libraryRef}>
        <mesh
          geometry={nodes["02_library"].geometry}
          material={materials["02"]}
        />
      </group>

      <group position={[-1.97, 4.227, -2.199]} ref={atticRef}>
        <mesh
          geometry={nodes["03_attic"].geometry}
          material={materials["03"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/WawaOffice.glb");

export default Office;
